#===============================================
#   Full list of mpv's default keybinds:
#   https://github.com/mpv-player/mpv/blob/master/etc/input.conf
#===============================================
c cycle sub-visibility                      # Cycle subtitle visibility
C cycle sub                                 # Switch subtitle track
l cycle-values loop-file inf no             # Toggle loop
WHEEL_UP add volume 5                       # Raises volume by 5%
WHEEL_DOWN add volume -5                    # Decreases volume by 5%

# >>> DISABLED KEYBINDS <<<
v ignore                                    # [DEFAULT] Cycle subtitle visibility
j ignore                                    # [DEFAULT] Switch subtitle track
q ignore                                    # [DEFAULT] Quit mpv
Ctrl+c ignore                               # [DEFAULT] Quit mpv
MBTN_RIGHT ignore                           # [DEFAULT] Pause/unpause playback
