#===============================================
#   GENERAL BEHAVIOR
#===============================================
window-maximized=yes                # Always open maximized
keep-open=yes                       # Keep mpv open when playback finishes
loop-file=inf                       # Loop current file by default
input-ipc-server=/tmp/mpv.sock      # Wrapper for single instance behavior

#===============================================
#   ON SCREEN DISPLAY/CONTROLLER
#===============================================
osc=no                              # Disable default OSC to allow a custom one
osd-bar=no                          # Disable giant volume/seek bar

#===============================================
#   SUBTITLES
#===============================================
sub-font="Netflix Sans Medium"
sub-font-size=40
sub-color="#FFFFFFFF"
sub-border-color="#FF000000"
sub-border-size=2.0
sub-shadow-color="#A0000000"
sub-shadow-offset=0.75
sub-spacing=0.0
sub-bold=no

#===============================================
#   CACHE
#===============================================
cache=no
cache-on-disk=no

#===============================================
#   YT-DLP
#===============================================
ytdl-format=bestvideo[height<=1080]+bestaudio/best[height<=1080]    # Always pick 1080p as default
